// Tests for the C++ safety filter.
//
// Two kinds of test here, and the split is deliberate:
//
//   * **Property tests** assert what must be true of any correct filter. The
//     box constraint in particular must hold on every iterate, not merely at
//     convergence, because the filter runs under a deadline and may be cut
//     short.
//   * **Golden tests** compare against the Python reference, case by case,
//     using values generated by tools/generate_golden.py. These are what stop
//     the two implementations drifting apart while each continues to look
//     correct on its own.

#include <gtest/gtest.h>

#include <Eigen/Dense>
#include <cmath>
#include <random>
#include <string>

#include "golden_cases.hpp"
#include "stretchwbc/safety_filter.hpp"

namespace stretchwbc {
namespace {

JointVector velocity_limit() {
  JointVector v;
  for (int i = 0; i < kNumJoints; ++i) {
    v(i) = testing::kVelocityLimit[i];
  }
  return v;
}

SafetyFilter make_filter() {
  return SafetyFilter(velocity_limit(), testing::kNumSoftRows);
}

// ------------------------------------------------------------- construction

TEST(SafetyFilter, RejectsNonPositiveVelocityLimits) {
  JointVector bad = velocity_limit();
  bad(3) = 0.0;
  EXPECT_THROW(SafetyFilter(bad, 4), std::invalid_argument);
}

TEST(SafetyFilter, RejectsMismatchedSoftBlock) {
  auto filter = make_filter();
  EXPECT_THROW(
      filter.set_soft_constraints(Eigen::MatrixXd::Zero(3, kNumJoints),
                                  Eigen::VectorXd::Zero(2)),
      std::invalid_argument);
}

TEST(SafetyFilter, RejectsMoreSoftRowsThanReserved) {
  SafetyFilter filter(velocity_limit(), 2);
  EXPECT_THROW(
      filter.set_soft_constraints(Eigen::MatrixXd::Zero(5, kNumJoints),
                                  Eigen::VectorXd::Zero(5)),
      std::invalid_argument);
}

// ---------------------------------------------------------------- properties

TEST(SafetyFilter, FeasibleRequestPassesThroughUnchanged) {
  auto filter = make_filter();
  filter.set_soft_constraints(Eigen::MatrixXd::Zero(0, kNumJoints),
                              Eigen::VectorXd::Zero(0));

  JointVector desired = JointVector::Zero();
  desired(0) = 0.05;

  const auto result = filter.solve(desired);

  EXPECT_TRUE(result.dq.isApprox(desired, 1e-12));
  EXPECT_FALSE(result.modified());
}

TEST(SafetyFilter, ClipsToTheVelocityBox) {
  auto filter = make_filter();
  filter.set_soft_constraints(Eigen::MatrixXd::Zero(0, kNumJoints),
                              Eigen::VectorXd::Zero(0));

  const auto result = filter.solve(JointVector::Constant(50.0));

  for (int i = 0; i < kNumJoints; ++i) {
    EXPECT_LE(std::abs(result.dq(i)), velocity_limit()(i) + 1e-12);
  }
}

TEST(SafetyFilter, BoxHoldsEvenWhenStoppedAfterOneIteration) {
  // The property that makes this safe to run under a deadline. Every iterate
  // is projected onto the box, so an early stop costs accuracy against the
  // soft constraints and nothing at all against the velocity limits.
  std::mt19937 rng(20260920);
  std::uniform_real_distribution<double> uniform(-5.0, 5.0);

  for (int cap : {1, 2, 5, 40}) {
    SolverOptions options;
    options.max_iterations = cap;
    SafetyFilter filter(velocity_limit(), 6, options);

    Eigen::MatrixXd matrix(6, kNumJoints);
    Eigen::VectorXd bound(6);
    for (int r = 0; r < 6; ++r) {
      for (int c = 0; c < kNumJoints; ++c) {
        matrix(r, c) = uniform(rng);
      }
      bound(r) = uniform(rng);
    }
    filter.set_soft_constraints(matrix, bound);

    for (int trial = 0; trial < 50; ++trial) {
      JointVector desired;
      for (int i = 0; i < kNumJoints; ++i) {
        desired(i) = uniform(rng);
      }

      const auto result = filter.solve(desired);
      for (int i = 0; i < kNumJoints; ++i) {
        EXPECT_GE(result.dq(i), filter.box_lower()(i) - 1e-12)
            << "cap=" << cap << " joint=" << i;
        EXPECT_LE(result.dq(i), filter.box_upper()(i) + 1e-12)
            << "cap=" << cap << " joint=" << i;
      }
    }
  }
}

TEST(SafetyFilter, InfeasibleSoftConstraintReportsSlack) {
  // A soft row no command inside the box can satisfy. The filter must still
  // return something executable and say how far short it fell.
  SafetyFilter filter(velocity_limit(), 1);

  Eigen::MatrixXd matrix(1, kNumJoints);
  matrix.setZero();
  matrix(0, 0) = 1.0;

  Eigen::VectorXd bound(1);
  bound(0) = -10.0;  // requires dq_0 <= -10, far outside the box

  filter.set_soft_constraints(matrix, bound);

  JointVector desired = JointVector::Zero();
  const auto result = filter.solve(desired);

  EXPECT_LE(std::abs(result.dq(0)), velocity_limit()(0) + 1e-12);
  EXPECT_GT(result.relaxed, 1.0);
}

TEST(SafetyFilter, SatisfiableSoftConstraintLeavesNoSlack) {
  SafetyFilter filter(velocity_limit(), 1);

  Eigen::MatrixXd matrix(1, kNumJoints);
  matrix.setZero();
  matrix(0, 0) = 1.0;

  Eigen::VectorXd bound(1);
  bound(0) = 0.05;

  filter.set_soft_constraints(matrix, bound);

  JointVector desired = JointVector::Zero();
  desired(0) = 0.2;

  const auto result = filter.solve(desired);

  EXPECT_LT(result.relaxed, 1e-3);
  EXPECT_LE(result.dq(0), 0.05 + 1e-3);
}

// -------------------------------------------------------------------- golden

class GoldenCaseTest : public ::testing::TestWithParam<int> {};

TEST_P(GoldenCaseTest, MatchesThePythonReference) {
  const auto& golden = testing::kGoldenCases[GetParam()];

  Eigen::MatrixXd matrix(testing::kNumSoftRows, kNumJoints);
  for (int r = 0; r < testing::kNumSoftRows; ++r) {
    for (int c = 0; c < kNumJoints; ++c) {
      matrix(r, c) = golden.soft_matrix[r * kNumJoints + c];
    }
  }

  Eigen::VectorXd bound(testing::kNumSoftRows);
  for (int r = 0; r < testing::kNumSoftRows; ++r) {
    bound(r) = golden.soft_bound[r];
  }

  JointVector desired;
  JointVector lower;
  JointVector upper;
  for (int i = 0; i < kNumJoints; ++i) {
    desired(i) = golden.desired[i];
    lower(i) = golden.box_lower[i];
    upper(i) = golden.box_upper[i];
  }

  auto filter = make_filter();
  filter.set_box(lower, upper);
  filter.set_soft_constraints(matrix, bound);

  const auto result = filter.solve(desired);

  for (int i = 0; i < kNumJoints; ++i) {
    EXPECT_NEAR(result.dq(i), golden.expected_dq[i], 1e-6)
        << "case=" << golden.name << " joint=" << i;
  }
}

INSTANTIATE_TEST_SUITE_P(
    AllCases, GoldenCaseTest,
    ::testing::Range(0, testing::kNumGoldenCases),
    [](const ::testing::TestParamInfo<int>& info) {
      return std::string(testing::kGoldenCases[info.param].name);
    });

// --------------------------------------------------------------- box bounds

TEST(SafetyFilter, NarrowedBoxIsRespected) {
  // What a joint-position barrier does: it tightens one joint's range. The
  // command must honour the narrowed bound, not the raw motor limit.
  auto filter = make_filter();
  filter.set_soft_constraints(Eigen::MatrixXd::Zero(0, kNumJoints),
                              Eigen::VectorXd::Zero(0));

  JointVector lower = -velocity_limit();
  JointVector upper = velocity_limit();
  upper(3) = 0.01;  // lift is nearly at its position limit
  filter.set_box(lower, upper);

  JointVector desired = JointVector::Zero();
  desired(3) = 1.0;

  const auto result = filter.solve(desired);

  EXPECT_LE(result.dq(3), 0.01 + 1e-12);
}

TEST(SafetyFilter, InvertedBoxCollapsesRatherThanThrowing) {
  // A joint already outside its position limit inverts the bound. Refusing to
  // answer is not an option for a safety filter, so the box collapses.
  auto filter = make_filter();

  JointVector lower = JointVector::Zero();
  JointVector upper = JointVector::Zero();
  lower(0) = 0.4;
  upper(0) = -0.2;

  EXPECT_NO_THROW(filter.set_box(lower, upper));
  EXPECT_DOUBLE_EQ(filter.box_lower()(0), 0.1);
  EXPECT_DOUBLE_EQ(filter.box_upper()(0), 0.1);
}

}  // namespace
}  // namespace stretchwbc
