"""Generate the C++ cross-check header from the Python reference.

    python tools/generate_golden.py

The C++ port in ``cpp/`` and the Python implementation in ``src/stretchwbc/``
solve the same problem with the same algorithm. Nothing about that is enforced
by the compiler, so it is enforced by data: this script runs the Python solver
on a fixed set of states and writes the answers into a header the gtest suite
compares against.

A port that quietly drifts from its reference is worse than no port, because
each looks correct when tested alone. Regenerate this header whenever the
Python solver changes, and expect the C++ tests to fail if the change was not
intended to alter behaviour.
"""

from __future__ import annotations

import pathlib

import numpy as np

from stretchwbc.model import N_JOINTS, StretchModel
from stretchwbc.safety import SafetyFilter, solve_box_soft_qp

OUTPUT = pathlib.Path(__file__).resolve().parent.parent / "cpp" / "test" / "golden_cases.hpp"
SEED = 20260920


def _fmt(values) -> str:
    return ", ".join(f"{x:.12g}" for x in np.asarray(values).ravel())


def build_cases(model: StretchModel, filt: SafetyFilter):
    rng = np.random.default_rng(SEED)
    home = (model.limits.lower + model.limits.upper) / 2.0

    states = []

    q = home.copy()
    states.append(("interior_small_request", q, np.array([0.05, 0, 0, 0.02, 0, 0, 0, 0])))
    states.append(("interior_huge_request", home.copy(), np.full(N_JOINTS, 9.0)))

    q = home.copy()
    q[3] = model.limits.upper[3] - 0.01
    states.append(("near_lift_limit", q, np.array([0, 0, 0, 1.0, 0, 0, 0, 0])))

    q = home.copy()
    q[4], q[3] = 0.36, 0.75
    states.append(("tipping_binds", q, np.array([0, 0, 0, 0.15, 0.15, 0, 0, 0])))

    q = home.copy()
    q[4], q[3] = 0.50, 1.00
    states.append(("outside_tipping_set", q, np.array([0, 0, 0, 0.1, 0.1, 0, 0, 0])))

    for i in range(3):
        q = model.limits.clamp(model.random_configuration(rng))
        states.append((f"random_{i}", q, rng.uniform(-3.0, 3.0, size=N_JOINTS)))

    return states


def main() -> None:
    model = StretchModel()
    filt = SafetyFilter(model)
    states = build_cases(model, filt)

    n_rows = filt.build_soft(states[0][1])[0].shape[0]
    if n_rows == 0:
        raise SystemExit("no coupling constraints; the golden cases would be vacuous")

    lines = [
        "// GENERATED by tools/generate_golden.py from the Python reference.",
        "// Do not edit by hand.",
        "//",
        "// These are the Python solver's answers on a fixed set of states. The C++",
        "// port is required to reproduce them. If a deliberate change to the Python",
        "// solver makes these fail, regenerate; if an accidental one does, that is",
        "// the header doing its job.",
        "",
        "#pragma once",
        "",
        "namespace stretchwbc::testing {",
        "",
        f"inline constexpr int kNumSoftRows = {n_rows};",
        "",
        "struct GoldenCase {",
        "  const char* name;",
        "  double q[8];",
        "  double desired[8];",
        "  double box_lower[8];",
        "  double box_upper[8];",
        f"  double soft_matrix[{n_rows} * 8];",
        f"  double soft_bound[{n_rows}];",
        "  double expected_dq[8];",
        "};",
        "",
        "inline const GoldenCase kGoldenCases[] = {",
    ]

    for name, q, desired in states:
        matrix, bound, _ = filt.build_soft(q)
        lower, upper = filt.build_box(q)
        solution = solve_box_soft_qp(desired, lower, upper, matrix, bound)

        lines += [
            f'    {{"{name}",',
            f"     {{{_fmt(q)}}},",
            f"     {{{_fmt(desired)}}},",
            f"     {{{_fmt(lower)}}},",
            f"     {{{_fmt(upper)}}},",
            f"     {{{_fmt(matrix)}}},",
            f"     {{{_fmt(bound)}}},",
            f"     {{{_fmt(solution.dq)}}}}},",
        ]

    lines += [
        "};",
        "",
        f"inline constexpr int kNumGoldenCases = {len(states)};",
        "",
        f"inline const double kVelocityLimit[8] = {{{_fmt(model.limits.velocity)}}};",
        "",
        "}  // namespace stretchwbc::testing",
        "",
    ]

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(states)} cases ({n_rows} soft rows) to {OUTPUT}")


if __name__ == "__main__":
    main()
