"""Write ros2/stretch_wbc_ros/test/controller_golden.hpp from the Python reference.

The ROS 2 package re-implements the kinematics, the Jacobian-transpose step and
the filter's box and tipping row in C++. This script evaluates the Python
versions on fixed cases and writes the answers into a header that the gtest
suite compares against. CI regenerates it and fails on any difference, so the
C++ port cannot drift from the reference unnoticed.

    python tools/generate_ros_golden.py
"""

from pathlib import Path

import numpy as np

from stretchwbc.model import StretchModel
from stretchwbc.safety import SafetyFilter, tipping_barrier

OUT = (
    Path(__file__).resolve().parents[1]
    / "ros2"
    / "stretch_wbc_ros"
    / "test"
    / "controller_golden.hpp"
)
MAX_STEP = 0.05


def jt_step(model: StretchModel, q: np.ndarray, target: np.ndarray) -> np.ndarray:
    """One iteration of stretchwbc.ik.solve_jacobian_transpose, before the joint clamp."""
    error = target - model.position(q)
    jacobian = model.position_jacobian(q)
    direction = jacobian.T @ error
    projected = jacobian @ direction
    step = float(error @ projected) / float(projected @ projected) * direction
    norm = float(np.linalg.norm(step))
    return step * (MAX_STEP / norm) if norm > MAX_STEP else step


def fmt(values) -> str:
    return "{" + ", ".join(f"{v:.17g}" for v in np.ravel(values)) + "}"


def main() -> None:
    model = StretchModel()
    flt = SafetyFilter(model)
    tipping = tipping_barrier()
    rng = np.random.default_rng(20261007)
    cases = []
    for _ in range(6):
        q = model.random_configuration(rng)
        target = model.position(model.random_configuration(rng))
        lower, upper = flt.build_box(q)
        cases.append(
            "  {"
            + ", ".join(
                [
                    fmt(q),
                    fmt(target),
                    fmt(model.position(q)),
                    fmt(model.position_jacobian(q)),  # row-major 3x8
                    fmt(jt_step(model, q, target)),
                    fmt(lower),
                    fmt(upper),
                    f"{tipping.margin(q):.17g}",
                ]
            )
            + "},"
        )
    header = [
        "// Generated by tools/generate_ros_golden.py from the Python reference. Do not edit.",
        "#pragma once",
        "",
        "#include <array>",
        "",
        "struct GoldenCase {",
        "  std::array<double, 8> q;",
        "  std::array<double, 3> target;",
        "  std::array<double, 3> position;",
        "  std::array<double, 24> jacobian;  // row-major 3x8",
        "  std::array<double, 8> jt_step;",
        "  std::array<double, 8> box_lower;",
        "  std::array<double, 8> box_upper;",
        "  double tipping_margin;",
        "};",
        "",
        "inline const GoldenCase kGoldenCases[] = {",
        *cases,
        "};",
        "",
    ]
    OUT.write_text("\n".join(header), encoding="utf-8", newline="\n")
    print(f"wrote {OUT} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
